apiVersion: v1
kind: Service
metadata:
  name: dotnet-kestrel
  namespace: dotnet-app
spec:
  type: ClusterIP
  selector:
    app: dotnet-kestrel
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
